version: '3.7'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app/love-psychology-terraform
      - $HOME/.aws:/root/.aws
      - $HOME/.ssh:/root/.ssh
